### ISSUE TITLE
Field order depends on JSON order

### ISSUE THREAD

**Issue by nesnoj** [rl-institut/meta_tool#1]
When pasting data into the JSON field, the order of fields shown in the tool follows the JSON order.
Instead, it should be in accordance to the [metadata standard](https://github.com/OpenEnergyPlatform/examples/wiki/Metadata-Description).

By the way: Is the meta tool up-to-date with the current metadata standard?

**Comment by henhuy** [comment]
> By the way: Is the meta tool up-to-date with the current metadata standard?

No, not yet updated!
Does this explains your bug? (Did not fully understand your problem)

**Comment by nesnoj** [comment]
No, it's not related to other mentioned problems.
The tool works fine, I just discovered an odd behavior which complicates the usage a little.

**Example**

Startup screen
________________________________________________
![image](https://user-images.githubusercontent.com/15910173/65140295-82c72f80-da0e-11e9-9854-166b463eea2d.png)
________________________________________________
After pasting a JSON ("Edit JSON") `{"name": "", "title": "Verwaltungsgebiete", "author": null, ...` it looks like
________________________________________________
![image](https://user-images.githubusercontent.com/15910173/65140377-b1dda100-da0e-11e9-82cf-891b1f8d5f57.png)
________________________________________________

As you can see the field order in the UI has changed ("temporal" is the first category now). Contrary to my first post, the order does not directly follow the order of the fields in the JSON. I dunno what the order depends on...

For users, it'd be great to have the very same order as in the [metadata standard](https://github.com/OpenEnergyPlatform/examples/wiki/Metadata-Description).

**Comment by henhuy** [comment]
Can you provide your whole JSON?
If you pass diverging keys/order meta logic gets messed up!
(try random JSON -> it outputs something, but not meta structure at all)

**Comment by nesnoj** [comment]
There u go.
This JSON was also created by the meta tool, hence is supposed to have a proper format.

```
        {"name": "", "title": "Verwaltungsgebiete", "author": null, "review": {"path": "none", "badge": "none"},
         "context": {"contact": "https://github.com/nesnoj", "grantNo": "03SFK4E1",
                     "homepage": "https://reiner-lemoine-institut.de/kopernikus-projekt-enavi/",
                     "sourceCode": "https://github.com/rl-institut/WAM_APP_stemp_abw",
                     "documentation": "https://github.com/rl-institut/WAM_APP_stemp_abw"}, "sources": [
            {"path": "http://www.geodatenzentrum.de/geodaten/gdz?l=down_opendata",
             "title": "Verwaltungsgebiete 1:250.000",
             "license": "dl-de/by-2-0", "copyright": "\u00a9 GeoBasis-DE / BKG 2016",
             "description": "Der Datenbestand umfasst s\u00e4mtliche Verwaltungseinheiten aller hierarchischen Verwaltungsebenen vom Staat bis zu den Gemeinden mit ihren Verwaltungsgrenzen, statistischen Schl\u00fcsselzahlen und dem Namen der Verwaltungseinheit sowie der spezifischen Bezeichnung der Verwaltungsebene des jeweiligen Bundeslandes."}],
         "spatial": {"extent": "Anhalt-Bitterfeld-Wittenberg", "location": "none", "resolution": "100 m"},
         "_comment": {"none": "If not applicable use (none)",
                      "dates": "Dates and time must follow the ISO8601 including time zone (YYYY-MM-DD or YYYY-MM-DDThh:mm:ss\u00b1hh)",
                      "units": "Use a space between numbers and units (100 m)",
                      "review": "Following the OEP Data Review (https://github.com/OpenEnergyPlatform/data-preprocessing/wiki)",
                      "licenses": "License name must follow the SPDX License List (https://spdx.org/licenses/)",
                      "metadata": "Metadata documentation and explanation (https://github.com/OpenEnergyPlatform/organisation/wiki/metadata)",
                      "languages": "Languages must follow the IETF (BCP47) format (en-GB, en-US, de-DE)"},
         "keywords": ["Landkreis", "Verwaltungsgebiet", "Gemeinde"], "language": "de-DE", "licenses": [
            {"id": "dl-de/by-2-0", "name": "dl-de/by-2-0", "path": "http://www.govdata.de/dl-de/by-2-0",
             "title": "Open Data Datenlizenz Deutschland \u2013 Namensnennung \u2013 Version 2.0",
             "attribution": "\u00a9 GeoBasis-DE / BKG 2016 (Daten ver\u00e4ndert)",
             "instruction": "Die hier angebotenen Geodaten stehen \u00fcber Geodatendienste gem\u00e4\u00df der Open Data Datenlizenz Deutschland \u2013 Namensnennung \u2013 Version 2.0 geldleistungsfrei zum Download und zur Online-Nutzung zur Verf\u00fcgung."}],
         "temporal": {"end": "", "start": "", "resolution": "none", "referenceDate": "2018-12-31"}, "resources": [],
         "identifier": "", "description": "Verwaltungsgebiete in Anhalt-Bitterfeld-Wittenberg", "contributors": [
            {"date": "2018-12-31", "email": "none", "title": "nesnoj", "object": "", "comment": "Metadata added"}],
         "metaMetadata": {
             "metadataLicense": {"name": "CC0-1.0", "path": "https://creativecommons.org/publicdomain/zero/1.0/",
                                 "title": "Creative Commons Zero v1.0 Universal"}, "metadataVersion": "OEP-1.4"},
         "publicationDate": "2018-12-31"}
```
(I indented for better readability)

**Comment by henhuy** [comment]
Bei mir klappt der import (fast) einwandfrei?!
(Außer das Feld "author", dass es im meta-tool nicht gibt)
Anscheinend habe ich das Meta-Tool zwischenzeitlich angepasst und die neue Version "versteht" dein JSON nicht komplett.
Aber zumindest sollte der Import bei dir und mir nicht unterschiedlich sein??

**Comment by henhuy** [comment]
But stop!
Your startup screen already look different to mine:
![image](https://user-images.githubusercontent.com/17476051/65142822-dab46500-da13-11e9-9746-1e869c6216f3.png)

??

**Comment by henhuy** [comment]
Just to rule out some mistakes: you are using meta-creator from our internal server, right?

**Comment by nesnoj** [comment]
> Just to rule out some mistakes: you are using meta-creator from our internal server, right?

Yepp!

**Comment by henhuy** [comment]
hmm maybe some dict or JSON ordering goes wrong (but since python 3.6 or 3.7 ordering is preserved anyway)?!
I think, I have to see/investigate this on your machine to identify the bug..

**Comment by nesnoj** [comment]
> I think, I have to see/investigate this on your machine to identify the bug..

It's not running locally but on the internal server (http://192.168.11.220:8001/meta_creator/), did you use it for the screenie above and is it up-to-date?

**Comment by henhuy** [comment]
> > I think, I have to see/investigate this on your machine to identify the bug..
> 
> It's not running locally but on the internal server (http://192.168.11.220:8001/meta_creator/), did you use it for the screenie above and is it up-to-date?

Yes, I used it for the screenie and
No, it is not up-to-date - some changes are missing

**Comment by nesnoj** [comment]
> Yes, I used it for the screenie

Hmm, that's really odd!

> No, it is not up-to-date - some changes are missing

Are the changes critical?

BTW, the tool is used today by @Stefanie08 to continue working on the sources. Please notify if you intend to update anything..

**Comment by Ludee** [comment]
This issue seems to be solved in the current version. The JSON order is correct. Reopen if another aspect is not covered yet.
