### ISSUE TITLE
The metadata version is not up to date (v1.4.1)

### ISSUE THREAD

**Issue by Ludee** [rl-institut/meta_tool#2]
- [x] Update to newest version: https://github.com/OpenEnergyPlatform/oemetadata/releases/tag/v1.4.1-fixed

- [x] If possible, include #1.

- [x] Release.

**Comment by henhuy** [comment]
@jh-RLI , could you take over this task - as I'm currently working on important issue which is needed in user tests...
To update meta data, this file has to be changed:
https://github.com/rl-institut/meta_tool/blob/master/static/meta_v4.json

Would be great, if you could start!

**Comment by Ludee** [comment]
I do the update in GitHub. Will assign you in the PR to merge and deploy.

**Comment by Ludee** [comment]
New version should be implemented.
I also found the schema used in the OEP and copied from there:
https://github.com/OpenEnergyPlatform/oeplatform/blob/develop/dataedit/static/metaedit/schema.json

I could not test it because could not run the Django app locally.

**Comment by Ludee** [comment]
Test successful. All fields and functions are working and the result matches current OEM version 1.4.1.
Big thanks to @henhuy

**Comment by Ludee** [comment]
I found a minor bug I created:

The date fields in **temporal** cannot be set to none.
Add none or date.
