### ISSUE TITLE
Update to new OEM version

### ISSUE THREAD

**Issue by Ludee** [rl-institut/meta_tool#5]
https://github.com/OpenEnergyPlatform/oemetadata/releases/tag/v1.5.0

**Comment by Ludee** [comment]
New version has been implemented and published.
Several bugs could be found in a first test:

- [ ] multiple _timeseries_
- [ ] default "null" bei leeren Feldern
- [ ] _@context_
- [ ] _language_
- [ ] fields: _is_about_ and _value_reference_

**Comment by jh-RLI** [comment]
Please assign me to this issue cant do it myself for some reason. @Ludee

**Comment by jh-RLI** [comment]
Cant commit my changes! can someone add me to this repo so I can push? @Ludee @henhuy

**Comment by jh-RLI** [comment]
The only thing I could not fix is the default value for all empty fields (null). Django json forms provides functions to set the "default": "null", however this is not the desired function, as we don't want to assign null as a string to each empty field.

e.g.: false: "id": "null" correct: "id": null
